# Generated by Django 2.1 on 2018-11-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
    ]
