# Generated by Django 2.1.3 on 2018-12-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='product',
            new_name='articles',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_detail',
        ),
    ]
