# Generated by Django 2.1.3 on 2018-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterfowl', '0002_remove_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
